// Mocks generated by Mockito 5.4.6 from annotations
// in language_duel/test/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i4;

import 'package:language_duel/services/api_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRegisterResult_0 extends _i1.SmartFake
    implements _i2.RegisterResult {
  _FakeRegisterResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfirmEmailResult_1 extends _i1.SmartFake
    implements _i2.ConfirmEmailResult {
  _FakeConfirmEmailResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResult_2 extends _i1.SmartFake implements _i2.LoginResult {
  _FakeLoginResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserDto_3 extends _i1.SmartFake implements _i2.UserDto {
  _FakeUserDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGameHistoryDetailDto_4 extends _i1.SmartFake
    implements _i2.GameHistoryDetailDto {
  _FakeGameHistoryDetailDto_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTicketDto_5 extends _i1.SmartFake implements _i2.TicketDto {
  _FakeTicketDto_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.RegisterResult> register({
    required String? email,
    required String? password,
    required String? confirmPassword,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #password: password,
              #confirmPassword: confirmPassword,
              #name: name,
            }),
            returnValue: _i3.Future<_i2.RegisterResult>.value(
              _FakeRegisterResult_0(
                this,
                Invocation.method(#register, [], {
                  #email: email,
                  #password: password,
                  #confirmPassword: confirmPassword,
                  #name: name,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.RegisterResult>);

  @override
  _i3.Future<_i2.ConfirmEmailResult> confirmEmail({
    required String? userId,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmEmail, [], {
              #userId: userId,
              #code: code,
            }),
            returnValue: _i3.Future<_i2.ConfirmEmailResult>.value(
              _FakeConfirmEmailResult_1(
                this,
                Invocation.method(#confirmEmail, [], {
                  #userId: userId,
                  #code: code,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.ConfirmEmailResult>);

  @override
  _i3.Future<void> resendConfirmEmail({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#resendConfirmEmail, [], {#userId: userId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.LoginResult> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i3.Future<_i2.LoginResult>.value(
              _FakeLoginResult_2(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.LoginResult>);

  @override
  _i3.Future<_i2.UserDto> getUser({
    required String? userId,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [], {#userId: userId, #token: token}),
            returnValue: _i3.Future<_i2.UserDto>.value(
              _FakeUserDto_3(
                this,
                Invocation.method(#getUser, [], {
                  #userId: userId,
                  #token: token,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.UserDto>);

  @override
  _i3.Future<void> updateProfileWithAvatar({
    required String? token,
    String? name,
    _i4.Uint8List? imageBytes,
    String? imageName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfileWithAvatar, [], {
              #token: token,
              #name: name,
              #imageBytes: imageBytes,
              #imageName: imageName,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateProfile({
    required String? token,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {#token: token, #name: name}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.LoginResult> googleLogin(String? idToken) =>
      (super.noSuchMethod(
            Invocation.method(#googleLogin, [idToken]),
            returnValue: _i3.Future<_i2.LoginResult>.value(
              _FakeLoginResult_2(
                this,
                Invocation.method(#googleLogin, [idToken]),
              ),
            ),
          )
          as _i3.Future<_i2.LoginResult>);

  @override
  _i3.Future<List<_i2.LeaderboardItemDto>> getLeaderboard({
    String? languageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLeaderboard, [], {#languageId: languageId}),
            returnValue: _i3.Future<List<_i2.LeaderboardItemDto>>.value(
              <_i2.LeaderboardItemDto>[],
            ),
          )
          as _i3.Future<List<_i2.LeaderboardItemDto>>);

  @override
  _i3.Future<List<_i2.UserAdminListItemDto>> getAllUsers({
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, [], {#token: token}),
            returnValue: _i3.Future<List<_i2.UserAdminListItemDto>>.value(
              <_i2.UserAdminListItemDto>[],
            ),
          )
          as _i3.Future<List<_i2.UserAdminListItemDto>>);

  @override
  _i3.Future<void> banUser({
    required String? token,
    required String? userId,
    required int? days,
    required String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#banUser, [], {
              #token: token,
              #userId: userId,
              #days: days,
              #reason: reason,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> unbanUser({
    required String? token,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#unbanUser, [], {#token: token, #userId: userId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i2.GameHistoryListItemDto>> getGamesHistory({
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGamesHistory, [], {#token: token}),
            returnValue: _i3.Future<List<_i2.GameHistoryListItemDto>>.value(
              <_i2.GameHistoryListItemDto>[],
            ),
          )
          as _i3.Future<List<_i2.GameHistoryListItemDto>>);

  @override
  _i3.Future<_i2.GameHistoryDetailDto> getGameHistory({
    required String? token,
    required String? gameId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGameHistory, [], {
              #token: token,
              #gameId: gameId,
            }),
            returnValue: _i3.Future<_i2.GameHistoryDetailDto>.value(
              _FakeGameHistoryDetailDto_4(
                this,
                Invocation.method(#getGameHistory, [], {
                  #token: token,
                  #gameId: gameId,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.GameHistoryDetailDto>);

  @override
  _i3.Future<void> createTicket({
    required String? token,
    required String? message,
    String? ticketId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTicket, [], {
              #token: token,
              #message: message,
              #ticketId: ticketId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i2.TicketListItemDto>> getTicketsByUser({
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTicketsByUser, [], {#token: token}),
            returnValue: _i3.Future<List<_i2.TicketListItemDto>>.value(
              <_i2.TicketListItemDto>[],
            ),
          )
          as _i3.Future<List<_i2.TicketListItemDto>>);

  @override
  _i3.Future<_i2.TicketDto> getTicket({
    required String? token,
    required String? ticketId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTicket, [], {
              #token: token,
              #ticketId: ticketId,
            }),
            returnValue: _i3.Future<_i2.TicketDto>.value(
              _FakeTicketDto_5(
                this,
                Invocation.method(#getTicket, [], {
                  #token: token,
                  #ticketId: ticketId,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.TicketDto>);

  @override
  _i3.Future<List<_i2.TicketListItemDto>> getAdminTickets({
    required String? token,
    required String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAdminTickets, [], {
              #token: token,
              #status: status,
            }),
            returnValue: _i3.Future<List<_i2.TicketListItemDto>>.value(
              <_i2.TicketListItemDto>[],
            ),
          )
          as _i3.Future<List<_i2.TicketListItemDto>>);

  @override
  _i3.Future<void> replyToTicket({
    required String? token,
    required String? ticketId,
    required String? message,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replyToTicket, [], {
              #token: token,
              #ticketId: ticketId,
              #message: message,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addUserMessage({
    required String? token,
    required String? ticketId,
    required String? message,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addUserMessage, [], {
              #token: token,
              #ticketId: ticketId,
              #message: message,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> closeTicket({
    required String? token,
    required String? ticketId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#closeTicket, [], {
              #token: token,
              #ticketId: ticketId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
